%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
:- assert(
robot_activity_experience(
	
	1100,					%% episode ID
	serve_coffee_to_guest4,				%% problem
	[
		serve_coffee_to_guest(mug1,guest1,counter1),	%% Task
		%serve_coffee_to_guest(guest1,counter1),	%% Task
		[						%% KeyProps
			at_start(instance(armunnamedposture, armunnamedposture0)),
			%at_start(hasphysicalentity(on4, mug1)),
			at_start(instance(gripperclosedposture, gripperclosedposture0)),
			%at_start(hasrobot(robotat0, trixi1)),
			at_start(hasgripperposture(rightgripper1, gripperclosedposture0)),
			at_start(instance(armunnamedposture, armunnamedposture1)),
			%at_start(instance(robotat, robotat0)),
			%at_start(hasarea(on4, placingareaeastrightcounter1)),
			at_start(on(mug1, placingareaeastrightcounter1)),
			at_start(hastorsoposture(torso1, torsodownposture0)),
			at_start(hasarmposture(leftarm1, armunnamedposture0)),
			%at_start(instance(on, on4)),
			%at_start(hasarea(robotat0, floorareatamsrestaurant1)),
			at_start(robotat(trixi1, floorareatamsrestaurant1)),
			at_start(hasarmposture(rightarm1, armunnamedposture1)),
			at_start(instance(torsodownposture, torsodownposture0)),
			throughout(haspremanipulationarea(table1, premanipulationareasouthtable1)),
			throughout(instance(table, table1)),
			throughout(instance(arm, leftarm1)),
			throughout(hasplacingarearight(sittingareawesttable1, placingareawestrighttable1)),
			throughout(instance(placingarea, placingareasouthrighttable2)),
			throughout(hasplacingarea(table2, placingareanorthlefttable2)),
			throughout(hasplacingarea(table1, placingareaeastlefttable1)),
			throughout(hasplacingarearight(sittingareasouthtable2, placingareasouthrighttable2)),
			throughout(haspremanipulationarea(manipulationareaeastcounter1, premanipulationareaeastcounter1)),
			throughout(hasmanipulationarea(table1, manipulationareasouthtable1)),
			throughout(instance(floorarea, floorareatamsrestaurant1)),
			throughout(instance(placingarea, placingareawestlefttable1)),
			throughout(hasplacingarea(table1, placingareawestlefttable1)),
			throughout(hasmanipulationarea(placingareasouthlefttable2, manipulationareawesttable2)),
			%throughout(instance(on, on2)),
			throughout(instance(manipulationarea, manipulationareanorthtable1)),
			%throughout(hasarea(on3, nearareatable2)),
			throughout(hasgripper(leftarm1, leftgripper1)),
			throughout(instance(torsoupposture, dummytorsoupposture)),
			throughout(instance(premanipulationarea, premanipulationareaeasttable2)),
			throughout(haspremanipulationarea(table2, premanipulationareawesttable2)),
			throughout(hasmanipulationareawest(table2, manipulationareawesttable2)),
			throughout(hasplacingarea(counter1, placingareaeastrightcounter1)),
			throughout(at(guest1, sittingareawesttable1)),
			throughout(hasplacingarealeft(sittingareanorthtable2, placingareanorthlefttable2)),
			throughout(hasplacingarea(table2, placingareasouthrighttable2)),
			%throughout(hasarea(on2, nearareatable1)),
			throughout(hassittingarea(table2, sittingareasouthtable2)),
			throughout(instance(armcarryposture, dummyarmcarryposture)),
			throughout(haspremanipulationarea(manipulationareasouthtable1, premanipulationareasouthtable1)),
			throughout(instance(premanipulationarea, premanipulationareawesttable2)),
			throughout(hasmanipulationarea(placingareaeastrightcounter1, manipulationareaeastcounter1)),
			throughout(hasmanipulationarea(placingareawestlefttable1, manipulationareanorthtable1)),
			throughout(haspremanipulationarea(table2, premanipulationareaeasttable2)),
			throughout(hasmanipulationarea(placingareaeastlefttable1, manipulationareasouthtable1)),
			throughout(instance(guest, guest1)),
			throughout(hasplacingarealeft(sittingareawesttable1, placingareawestlefttable1)),
			throughout(hasmanipulationarea(placingareaeastrighttable1, manipulationareanorthtable1)),
			throughout(instance(torso, torso1)),
			throughout(hasplacingarealeft(sittingareasouthtable2, placingareasouthlefttable2)),
			throughout(instance(premanipulationarea, premanipulationareanorthtable1)),
			throughout(instance(sittingarea, sittingareanorthtable2)),
			throughout(instance(sittingarea, sittingareasouthtable2)),
			throughout(hasmanipulationarea(placingareawestrighttable1, manipulationareasouthtable1)),
			throughout(instance(placingarea, placingareawestrighttable1)),
			throughout(hasmanipulationarea(counter1, manipulationareaeastcounter1)),
			throughout(instance(mug, mug1)),
			throughout(instance(sittingarea, sittingareawesttable1)),
			throughout(instance(armtuckedposture, dummyarmtuckedposture)),
			%throughout(hasphysicalentity(at1, guest1)),
			%throughout(hasphysicalentity(on2, table1)),
			throughout(hasmanipulationarea(placingareanorthrighttable2, manipulationareawesttable2)),
			throughout(haspremanipulationarea(manipulationareawesttable2, premanipulationareawesttable2)),
			throughout(hasmanipulationareasouth(table1, manipulationareasouthtable1)),
			throughout(hasplacingarea(table1, placingareawestrighttable1)),
			%throughout(hasphysicalentity(on3, table2)),
			throughout(haspremanipulationarea(table1, premanipulationareanorthtable1)),
			throughout(instance(arm, rightarm1)),
			throughout(hasmanipulationarea(table2, manipulationareaeasttable2)),
			throughout(haspremanipulationarea(manipulationareanorthtable1, premanipulationareanorthtable1)),
			throughout(hasplacingarearight(sittingareanorthtable2, placingareanorthrighttable2)),
			throughout(instance(gripperclosedposture, gripperclosedposture1)),
			throughout(instance(manipulationarea, manipulationareaeasttable2)),
			throughout(instance(table, table2)),
			throughout(instance(placingarea, placingareaeastlefttable1)),
			throughout(haspremanipulationarea(manipulationareaeasttable2, premanipulationareaeasttable2)),
			%throughout(hasphysicalentity(on1, counter1)),
			throughout(hasmanipulationareanorth(table1, manipulationareanorthtable1)),
			throughout(hasplacingarea(table2, placingareanorthrighttable2)),
			throughout(hassittingarea(table1, sittingareawesttable1)),
			throughout(hasplacingarealeft(sittingareaeasttable1, placingareaeastlefttable1)),
			%throughout(hasarea(at1, sittingareawesttable1)),
			throughout(hasplacingarea(table2, placingareasouthlefttable2)),
			throughout(hasgripper(rightarm1, rightgripper1)),
			throughout(hasplacingarea(table1, placingareaeastrighttable1)),
			throughout(instance(manipulationarea, manipulationareasouthtable1)),
			throughout(instance(gripper, leftgripper1)),
			throughout(hassittingarea(table2, sittingareanorthtable2)),
			throughout(hasmanipulationarea(placingareanorthlefttable2, manipulationareaeasttable2)),
			throughout(hasmanipulationarea(placingareasouthrighttable2, manipulationareaeasttable2)),
			throughout(instance(counter, counter1)),
			throughout(hassittingarea(table1, sittingareaeasttable1)),
			%throughout(instance(on, on3)),
			throughout(instance(torsomiddleposture, dummytorsomiddleposture)),
			throughout(hasmanipulationareaeast(table2, manipulationareaeasttable2)),
			throughout(instance(armuntuckedposture, dummyarmuntuckedposture)),
			throughout(hasgripperposture(leftgripper1, gripperclosedposture1)),
			throughout(instance(premanipulationarea, premanipulationareasouthtable1)),
			throughout(instance(manipulationarea, manipulationareaeastcounter1)),
			throughout(instance(placingarea, placingareanorthrighttable2)),
			throughout(instance(manipulationarea, manipulationareawesttable2)),
			throughout(instance(placingarea, placingareaeastrightcounter1)),
			throughout(instance(placingarea, placingareanorthlefttable2)),
			throughout(instance(sittingarea, sittingareaeasttable1)),
			throughout(instance(placingarea, placingareaeastrighttable1)),
			%throughout(instance(at, at1)),
			throughout(hasmanipulationarea(table2, manipulationareawesttable2)),
			throughout(instance(placingarea, placingareasouthlefttable2)),
			throughout(instance(premanipulationarea, premanipulationareaeastcounter1)),
			throughout(hasplacingarearight(sittingareaeasttable1, placingareaeastrighttable1)),
			throughout(instance(gripper, rightgripper1)),
			%throughout(hasarea(on1, nearareacounter1)),
			throughout(hasmanipulationarea(table1, manipulationareanorthtable1)),
			%throughout(instance(on, on1)),
			at_end(instance(torsoupposture, torsoupposture6)),
			at_end(hasgripperposture(rightgripper1, gripperopeningposture8)),
			at_end(hasarmposture(leftarm1, armcarryposture37)),
			%at_end(hasarea(on_0x0, placingareawestrighttable1)),
			at_end(on(mug1, placingareawestrighttable1)),
			at_end(instance(gripperopeningposture, gripperopeningposture8)),
			%at_end(instance(robotat, robotat15)),
			%at_end(instance(on, on_0x0)),
			%at_end(hasphysicalentity(on_0x0, mug1)),
			at_end(instance(armcarryposture, armcarryposture37)),
			at_end(instance(armtosideposture, armtosideposture53)),
			%at_end(hasarea(robotat15, manipulationareasouthtable1)),
			at_end(robotat(trixi1, manipulationareasouthtable1)),
			at_end(hastorsoposture(torso1, torsoupposture6)),
			at_end(hasarmposture(rightarm1, armtosideposture53))
			%at_end(hasrobot(robotat15, trixi1))
		],
		none,				%% failed operation
		race_dummy,			%% failure type
		[
			tuck_arms(leftarm1, rightarm1, armunnamedposture, armunnamedposture, armunnamedposture0, armunnamedposture1, armtuckedposture, armtuckedposture, armtuckedposture7, armtuckedposture13),
			move_base(floorareatamsrestaurant1, premanipulationareaeastcounter1),
			move_torso(torso1, torsodownposture, torsodownposture0, torsoupposture, torsoupposture2),
			tuck_arms(leftarm1, rightarm1, armtuckedposture, armtuckedposture, armtuckedposture7, armtuckedposture13, armuntuckedposture, armtuckedposture, armuntuckedposture5, armtuckedposture1002),
			move_arm_to_side(leftarm1, armuntuckedposture, armuntuckedposture5, armtosideposture21),
			move_arm_to_side(rightarm1, armuntuckedposture, armuntuckedposture9, armtosideposture23),
			move_base_blind_to_ma(premanipulationareaeastcounter1, manipulationareaeastcounter1),
			%observe_objects_on_area(placingareaeastrightcounter1, manipulationareaeastcounter1),
			pick_up_object(mug1, rightarm1, manipulationareaeastcounter1, placingareaeastrightcounter1, rightgripper1, gripperopeningposture1, gripperholdingposture2, torsoupposture2, armtosideposture23),
			move_base_blind_to_pma(manipulationareaeastcounter1, premanipulationareaeastcounter1),
			move_arms_to_carryposture(leftarm1, rightarm1, armtosideposture, armtosideposture, armtosideposture21, armtosideposture23, armcarryposture37, armcarryposture39),
			move_torso(torso1, torsoupposture, torsoupposture2, torsomiddleposture, torsomiddleposture4),
			move_base(premanipulationareaeastcounter1, premanipulationareasouthtable1),
			move_torso(torso1, torsomiddleposture, torsomiddleposture4, torsoupposture, torsoupposture6),
			move_arm_to_side(rightarm1, armcarryposture, armcarryposture39, armtosideposture53),
			move_base_blind_to_ma(premanipulationareasouthtable1, manipulationareasouthtable1),
			place_object(mug1, rightarm1, manipulationareasouthtable1, placingareawestrighttable1, rightgripper1, gripperholdingposture2, gripperopeningposture3, torsoupposture6, armtosideposture53),
			move_base_blind_to_pma(manipulationareasouthtable1, premanipulationareasouthtable1)
		]
	]
)).
	

%% serve_coffee loop
:- assert(
robot_activity_experience(
	
	1101,					%% episode ID
	serve_coffee_to_guest4,				%% problem
	[
		serve_coffee_to_guest(guest1,counter1),	%% Task
		[						%% KeyProps
			at_start(instance(armunnamedposture, armunnamedposture0)),
			%at_start(hasphysicalentity(on4, mug1)),
			at_start(instance(gripperclosedposture, gripperclosedposture0)),
			%at_start(hasrobot(robotat0, trixi1)),
			at_start(hasgripperposture(rightgripper1, gripperclosedposture0)),
			at_start(instance(armunnamedposture, armunnamedposture1)),
			%at_start(instance(robotat, robotat0)),
			%at_start(hasarea(on4, placingareaeastrightcounter1)),
			at_start(on(mug1, placingareaeastrightcounter1)),
			at_start(on(mug2, placingareaeastrightcounter1)),
			at_start(hastorsoposture(torso1, torsodownposture0)),
			at_start(hasarmposture(leftarm1, armunnamedposture0)),
			%at_start(instance(on, on4)),
			%at_start(hasarea(robotat0, floorareatamsrestaurant1)),
			at_start(robotat(trixi1, floorareatamsrestaurant1)),
			at_start(hasarmposture(rightarm1, armunnamedposture1)),
			at_start(instance(torsodownposture, torsodownposture0)),
			throughout(haspremanipulationarea(table1, premanipulationareasouthtable1)),
			throughout(instance(table, table1)),
			throughout(instance(arm, leftarm1)),
			throughout(hasplacingarearight(sittingareawesttable1, placingareawestrighttable1)),
			throughout(instance(placingarea, placingareasouthrighttable2)),
			throughout(hasplacingarea(table2, placingareanorthlefttable2)),
			throughout(hasplacingarea(table1, placingareaeastlefttable1)),
			throughout(hasplacingarearight(sittingareasouthtable2, placingareasouthrighttable2)),
			throughout(haspremanipulationarea(manipulationareaeastcounter1, premanipulationareaeastcounter1)),
			throughout(hasmanipulationarea(table1, manipulationareasouthtable1)),
			throughout(instance(floorarea, floorareatamsrestaurant1)),
			throughout(instance(placingarea, placingareawestlefttable1)),
			throughout(hasplacingarea(table1, placingareawestlefttable1)),
			throughout(hasmanipulationarea(placingareasouthlefttable2, manipulationareawesttable2)),
			%throughout(instance(on, on2)),
			throughout(instance(manipulationarea, manipulationareanorthtable1)),
			%throughout(hasarea(on3, nearareatable2)),
			throughout(hasgripper(leftarm1, leftgripper1)),
			throughout(instance(torsoupposture, dummytorsoupposture)),
			throughout(instance(premanipulationarea, premanipulationareaeasttable2)),
			throughout(haspremanipulationarea(table2, premanipulationareawesttable2)),
			throughout(hasmanipulationareawest(table2, manipulationareawesttable2)),
			throughout(hasplacingarea(counter1, placingareaeastrightcounter1)),
			throughout(at(guest1, sittingareawesttable1)),
			throughout(hasplacingarealeft(sittingareanorthtable2, placingareanorthlefttable2)),
			throughout(hasplacingarea(table2, placingareasouthrighttable2)),
			%throughout(hasarea(on2, nearareatable1)),
			throughout(hassittingarea(table2, sittingareasouthtable2)),
			throughout(instance(armcarryposture, dummyarmcarryposture)),
			throughout(haspremanipulationarea(manipulationareasouthtable1, premanipulationareasouthtable1)),
			throughout(instance(premanipulationarea, premanipulationareawesttable2)),
			throughout(hasmanipulationarea(placingareaeastrightcounter1, manipulationareaeastcounter1)),
			throughout(hasmanipulationarea(placingareawestlefttable1, manipulationareanorthtable1)),
			throughout(haspremanipulationarea(table2, premanipulationareaeasttable2)),
			throughout(hasmanipulationarea(placingareaeastlefttable1, manipulationareasouthtable1)),
			throughout(instance(guest, guest1)),
			throughout(hasplacingarealeft(sittingareawesttable1, placingareawestlefttable1)),
			throughout(hasmanipulationarea(placingareaeastrighttable1, manipulationareanorthtable1)),
			throughout(instance(torso, torso1)),
			throughout(hasplacingarealeft(sittingareasouthtable2, placingareasouthlefttable2)),
			throughout(instance(premanipulationarea, premanipulationareanorthtable1)),
			throughout(instance(sittingarea, sittingareanorthtable2)),
			throughout(instance(sittingarea, sittingareasouthtable2)),
			throughout(hasmanipulationarea(placingareawestrighttable1, manipulationareasouthtable1)),
			throughout(instance(placingarea, placingareawestrighttable1)),
			throughout(hasmanipulationarea(counter1, manipulationareaeastcounter1)),
			throughout(instance(mug, mug1)),
			throughout(instance(mug, mug2)),
			throughout(instance(sittingarea, sittingareawesttable1)),
			throughout(instance(armtuckedposture, dummyarmtuckedposture)),
			%throughout(hasphysicalentity(at1, guest1)),
			%throughout(hasphysicalentity(on2, table1)),
			throughout(hasmanipulationarea(placingareanorthrighttable2, manipulationareawesttable2)),
			throughout(haspremanipulationarea(manipulationareawesttable2, premanipulationareawesttable2)),
			throughout(hasmanipulationareasouth(table1, manipulationareasouthtable1)),
			throughout(hasplacingarea(table1, placingareawestrighttable1)),
			%throughout(hasphysicalentity(on3, table2)),
			throughout(haspremanipulationarea(table1, premanipulationareanorthtable1)),
			throughout(instance(arm, rightarm1)),
			throughout(hasmanipulationarea(table2, manipulationareaeasttable2)),
			throughout(haspremanipulationarea(manipulationareanorthtable1, premanipulationareanorthtable1)),
			throughout(hasplacingarearight(sittingareanorthtable2, placingareanorthrighttable2)),
			throughout(instance(gripperclosedposture, gripperclosedposture1)),
			throughout(instance(manipulationarea, manipulationareaeasttable2)),
			throughout(instance(table, table2)),
			throughout(instance(placingarea, placingareaeastlefttable1)),
			throughout(haspremanipulationarea(manipulationareaeasttable2, premanipulationareaeasttable2)),
			%throughout(hasphysicalentity(on1, counter1)),
			throughout(hasmanipulationareanorth(table1, manipulationareanorthtable1)),
			throughout(hasplacingarea(table2, placingareanorthrighttable2)),
			throughout(hassittingarea(table1, sittingareawesttable1)),
			throughout(hasplacingarealeft(sittingareaeasttable1, placingareaeastlefttable1)),
			%throughout(hasarea(at1, sittingareawesttable1)),
			throughout(hasplacingarea(table2, placingareasouthlefttable2)),
			throughout(hasgripper(rightarm1, rightgripper1)),
			throughout(hasplacingarea(table1, placingareaeastrighttable1)),
			throughout(instance(manipulationarea, manipulationareasouthtable1)),
			throughout(instance(gripper, leftgripper1)),
			throughout(hassittingarea(table2, sittingareanorthtable2)),
			throughout(hasmanipulationarea(placingareanorthlefttable2, manipulationareaeasttable2)),
			throughout(hasmanipulationarea(placingareasouthrighttable2, manipulationareaeasttable2)),
			throughout(instance(counter, counter1)),
			throughout(hassittingarea(table1, sittingareaeasttable1)),
			%throughout(instance(on, on3)),
			throughout(instance(torsomiddleposture, dummytorsomiddleposture)),
			throughout(hasmanipulationareaeast(table2, manipulationareaeasttable2)),
			throughout(instance(armuntuckedposture, dummyarmuntuckedposture)),
			throughout(hasgripperposture(leftgripper1, gripperclosedposture1)),
			throughout(instance(premanipulationarea, premanipulationareasouthtable1)),
			throughout(instance(manipulationarea, manipulationareaeastcounter1)),
			throughout(instance(placingarea, placingareanorthrighttable2)),
			throughout(instance(manipulationarea, manipulationareawesttable2)),
			throughout(instance(placingarea, placingareaeastrightcounter1)),
			throughout(instance(placingarea, placingareanorthlefttable2)),
			throughout(instance(sittingarea, sittingareaeasttable1)),
			throughout(instance(placingarea, placingareaeastrighttable1)),
			%throughout(instance(at, at1)),
			throughout(hasmanipulationarea(table2, manipulationareawesttable2)),
			throughout(instance(placingarea, placingareasouthlefttable2)),
			throughout(instance(premanipulationarea, premanipulationareaeastcounter1)),
			throughout(hasplacingarearight(sittingareaeasttable1, placingareaeastrighttable1)),
			throughout(instance(gripper, rightgripper1)),
			%throughout(hasarea(on1, nearareacounter1)),
			throughout(hasmanipulationarea(table1, manipulationareanorthtable1)),
			%throughout(instance(on, on1)),
			at_end(instance(torsoupposture, torsoupposture6)),
			at_end(hasgripperposture(rightgripper1, gripperopeningposture8)),
			at_end(hasarmposture(rightarm1, armtosideposture53)),
			%at_end(hasarea(on_0x0, placingareawestrighttable1)),
			at_end(on(mug1, placingareawestrighttable1)),
			at_end(on(mug2, placingareawestrighttable1)),
			at_end(instance(gripperopeningposture, gripperopeningposture8)),
			%at_end(instance(robotat, robotat15)),
			%at_end(instance(on, on_0x0)),
			%at_end(hasphysicalentity(on_0x0, mug1)),
			at_end(instance(armtosideposture, armtosideposture53)),
			at_end(instance(armtosideposture, armtosideposture54)),
			%at_end(hasarea(robotat15, manipulationareasouthtable1)),
			at_end(robotat(trixi1, manipulationareasouthtable1)),
			at_end(hastorsoposture(torso1, torsoupposture6)),
			at_end(hasarmposture(leftarm1, armtosideposture54))
			%at_end(hasrobot(robotat15, trixi1))
		],
		none,				%% failed operation
		race_dummy,			%% failure type
		[
			tuck_arms(leftarm1, rightarm1, armunnamedposture, armunnamedposture, armunnamedposture0, armunnamedposture1, armtuckedposture, armtuckedposture, armtuckedposture7, armtuckedposture13),
			move_base(floorareatamsrestaurant1, premanipulationareaeastcounter1),
			move_torso(torso1, torsodownposture, torsodownposture0, torsoupposture, torsoupposture2),
			tuck_arms(leftarm1, rightarm1, armtuckedposture, armtuckedposture, armtuckedposture7, armtuckedposture13, armuntuckedposture, armtuckedposture, armuntuckedposture5, armtuckedposture1002),
			move_arm_to_side(leftarm1, armuntuckedposture, armuntuckedposture5, armtosideposture21),
			move_arm_to_side(rightarm1, armuntuckedposture, armuntuckedposture9, armtosideposture23),
			move_base_blind_to_ma(premanipulationareaeastcounter1, manipulationareaeastcounter1),
			%observe_objects_on_area(placingareaeastrightcounter1, manipulationareaeastcounter1),
			pick_up_object(mug1, rightarm1, manipulationareaeastcounter1, placingareaeastrightcounter1, rightgripper1, gripperopeningposture1, gripperholdingposture2, torsoupposture2, armtosideposture23),
			pick_up_object(mug2, leftarm1, manipulationareaeastcounter1, placingareaeastrightcounter1, leftgripper1, gripperopeningposture3, gripperholdingposture4, torsoupposture2, armtosideposture21),
			move_base_blind_to_pma(manipulationareaeastcounter1, premanipulationareaeastcounter1),
			move_arms_to_carryposture(leftarm1, rightarm1, armtosideposture, armtosideposture, armtosideposture21, armtosideposture23, armcarryposture37, armcarryposture39),
			move_torso(torso1, torsoupposture, torsoupposture2, torsomiddleposture, torsomiddleposture4),
			move_base(premanipulationareaeastcounter1, premanipulationareasouthtable1),
			move_torso(torso1, torsomiddleposture, torsomiddleposture4, torsoupposture, torsoupposture6),
			move_arm_to_side(rightarm1, armcarryposture, armcarryposture39, armtosideposture53),
			move_arm_to_side(leftarm1, armcarryposture, armcarryposture37, armtosideposture54),
			move_base_blind_to_ma(premanipulationareasouthtable1, manipulationareasouthtable1),
			place_object(mug1, rightarm1, manipulationareasouthtable1, placingareawestrighttable1, rightgripper1, gripperholdingposture2, gripperopeningposture5, torsoupposture6, armtosideposture53),
			place_object(mug2, leftarm1, manipulationareasouthtable1, placingareawestrighttable1, leftgripper1, gripperholdingposture4, gripperopeningposture6, torsoupposture6, armtosideposture54),
			move_base_blind_to_pma(manipulationareasouthtable1, premanipulationareasouthtable1)
		]
	]
)).

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%% clear_table loop
:- assert(
robot_activity_experience(
	
	1152,					%% episode ID
	clear_table,				%% problem
	[
		clear_table(mug1,mug2,table1,counter1),	%% Task
		[						%% KeyProps
			at_start(instance(armunnamedposture, armunnamedposture0)),
			at_start(instance(gripperclosedposture, gripperclosedposture0)),
			at_start(hasgripperposture(leftgripper1, gripperclosedposture1)),
			at_start(on(mug1, placingareawestrighttable1)),
			at_start(on(mug2, placingareawestrighttable1)),
			at_start(robotat(trixi1, floorareatamsrestaurant1)),
			%at_start(instance(on, on6)),
			%at_start(hasarea(on5, placingareawestrighttable1)),
			%at_start(instance(on, on5)),
			%at_start(hasphysicalentity(on6, mug2)),
			%at_start(hasarea(on6, placingareaeastrighttable1)),
			%at_start(hasphysicalentity(on5, mug1)),
			%at_start(hasrobot(robotat0, trixi1)),
			%at_start(instance(robotat, robotat0)),
			%at_start(hasarea(robotat0, floorareatamsrestaurant1)),
			at_start(hasarmposture(rightarm1, armunnamedposture0)),
			at_start(hasgripperposture(rightgripper1, gripperclosedposture0)),
			at_start(instance(gripperclosedposture, gripperclosedposture1)),
			at_start(instance(armunnamedposture, armunnamedposture1)),
			at_start(hasarmposture(leftarm1, armunnamedposture1)),
			at_start(instance(torsodownposture, torsodownposture0)),
			at_start(hastorsoposture(torso1, torsodownposture0)),
			throughout(haspremanipulationarea(table1, premanipulationareasouthtable1)),
			throughout(instance(table, table1)),
			throughout(instance(arm, leftarm1)),
			throughout(hasplacingarearight(sittingareawesttable1, placingareawestrighttable1)),
			throughout(instance(placingarea, placingareasouthrighttable2)),
			throughout(hasplacingarea(table2, placingareanorthlefttable2)),
			throughout(hasplacingarea(table1, placingareaeastlefttable1)),
			throughout(hasplacingarearight(sittingareasouthtable2, placingareasouthrighttable2)),
			throughout(hasmanipulationareaeast(table2, manipulationareaeasttable2)),
			throughout(hasmanipulationarea(table1, manipulationareasouthtable1)),
			throughout(instance(placingarea, placingareawestlefttable1)),
			throughout(hasplacingarea(table1, placingareawestlefttable1)),
			throughout(hasmanipulationarea(placingareasouthlefttable2, manipulationareawesttable2)),
			%throughout(instance(on, on2)),
			throughout(instance(manipulationarea, manipulationareanorthtable1)),
			throughout(hasgripper(leftarm1, leftgripper1)),
			throughout(instance(premanipulationarea, premanipulationareaeasttable2)),
			throughout(haspremanipulationarea(table2, premanipulationareawesttable2)),
			throughout(hasmanipulationareawest(table2, manipulationareawesttable2)),
			throughout(hasplacingarea(counter1, placingareaeastrightcounter1)),
			throughout(hasplacingarealeft(sittingareanorthtable2, placingareanorthlefttable2)),
			throughout(hasplacingarea(table2, placingareasouthrighttable2)),
			%throughout(hasarea(on2, nearareatable1)),
			throughout(hassittingarea(table2, sittingareasouthtable2)),
			throughout(haspremanipulationarea(manipulationareasouthtable1, premanipulationareasouthtable1)),
			throughout(instance(premanipulationarea, premanipulationareawesttable2)),
			throughout(hasmanipulationarea(placingareaeastrightcounter1, manipulationareaeastcounter1)),
			throughout(hasmanipulationarea(placingareawestlefttable1, manipulationareanorthtable1)),
			throughout(haspremanipulationarea(table2, premanipulationareaeasttable2)),
			throughout(hasmanipulationarea(placingareaeastlefttable1, manipulationareasouthtable1)),
			throughout(hasplacingarealeft(sittingareawesttable1, placingareawestlefttable1)),
			throughout(hasmanipulationarea(placingareaeastrighttable1, manipulationareanorthtable1)),
			throughout(instance(torso, torso1)),
			throughout(hasplacingarealeft(sittingareasouthtable2, placingareasouthlefttable2)),
			throughout(instance(mug, mug2)),
			throughout(instance(premanipulationarea, premanipulationareanorthtable1)),
			throughout(instance(sittingarea, sittingareanorthtable2)),
			throughout(instance(sittingarea, sittingareasouthtable2)),
			throughout(hasmanipulationarea(placingareawestrighttable1, manipulationareasouthtable1)),
			throughout(instance(placingarea, placingareawestrighttable1)),
			throughout(hasmanipulationarea(counter1, manipulationareaeastcounter1)),
			throughout(instance(mug, mug1)),
			throughout(instance(sittingarea, sittingareawesttable1)),
			%throughout(hasphysicalentity(on2, table1)),
			throughout(hasmanipulationarea(placingareanorthrighttable2, manipulationareawesttable2)),
			throughout(haspremanipulationarea(manipulationareawesttable2, premanipulationareawesttable2)),
			throughout(hasmanipulationareasouth(table1, manipulationareasouthtable1)),
			throughout(hasplacingarea(table1, placingareawestrighttable1)),
			%throughout(hasphysicalentity(on3, table2)),
			throughout(haspremanipulationarea(table1, premanipulationareanorthtable1)),
			throughout(instance(arm, rightarm1)),
			throughout(hasmanipulationarea(table2, manipulationareaeasttable2)),
			throughout(haspremanipulationarea(manipulationareanorthtable1, premanipulationareanorthtable1)),
			throughout(hasplacingarearight(sittingareanorthtable2, placingareanorthrighttable2)),
			throughout(instance(manipulationarea, manipulationareaeasttable2)),
			throughout(instance(table, table2)),
			throughout(instance(placingarea, placingareaeastlefttable1)),
			throughout(haspremanipulationarea(manipulationareaeasttable2, premanipulationareaeasttable2)),
			%throughout(hasphysicalentity(on1, counter1)),
			throughout(hasmanipulationareanorth(table1, manipulationareanorthtable1)),
			throughout(hasplacingarea(table2, placingareanorthrighttable2)),
			throughout(hassittingarea(table1, sittingareawesttable1)),
			throughout(hasplacingarealeft(sittingareaeasttable1, placingareaeastlefttable1)),
			throughout(hasplacingarea(table2, placingareasouthlefttable2)),
			throughout(hasgripper(rightarm1, rightgripper1)),
			throughout(hasplacingarea(table1, placingareaeastrighttable1)),
			throughout(instance(manipulationarea, manipulationareasouthtable1)),
			throughout(instance(gripper, leftgripper1)),
			throughout(hassittingarea(table2, sittingareanorthtable2)),
			throughout(hasmanipulationarea(placingareanorthlefttable2, manipulationareaeasttable2)),
			throughout(hasmanipulationarea(placingareasouthrighttable2, manipulationareaeasttable2)),
			throughout(instance(counter, counter1)),
			throughout(hassittingarea(table1, sittingareaeasttable1)),
			%throughout(instance(on, on3)),
			%throughout(hasarea(on3, nearareatable2)),
			throughout(haspremanipulationarea(manipulationareaeastcounter1, premanipulationareaeastcounter1)),
			throughout(instance(premanipulationarea, premanipulationareasouthtable1)),
			throughout(instance(manipulationarea, manipulationareaeastcounter1)),
			throughout(instance(placingarea, placingareanorthrighttable2)),
			throughout(instance(manipulationarea, manipulationareawesttable2)),
			throughout(instance(placingarea, placingareaeastrightcounter1)),
			throughout(instance(placingarea, placingareanorthlefttable2)),
			throughout(instance(sittingarea, sittingareaeasttable1)),
			throughout(instance(placingarea, placingareaeastrighttable1)),
			throughout(hasmanipulationarea(table2, manipulationareawesttable2)),
			throughout(instance(placingarea, placingareasouthlefttable2)),
			throughout(instance(premanipulationarea, premanipulationareaeastcounter1)),
			throughout(hasplacingarearight(sittingareaeasttable1, placingareaeastrighttable1)),
			throughout(instance(gripper, rightgripper1)),
			%throughout(hasarea(on1, nearareacounter1)),
			throughout(hasmanipulationarea(table1, manipulationareanorthtable1)),
			%throughout(instance(on, on1)),
			at_end(instance(gripperopenedposture, gripperopenedposture12)),
			%at_end(hasrobot(robotat33, trixi1)),
			%at_end(hasarea(robotat33, premanipulationareaeastcounter1)),
			%at_end(instance(robotat, robotat33)),
			at_end(robotat(trixi1, premanipulationareaeastcounter1)),
			at_end(hasgripperposture(rightgripper1, gripperopenedposture15)),
			at_end(hasarmposture(rightarm1, armtosideposture115)),
			at_end(hasgripperposture(leftgripper1, gripperopenedposture12)),
			at_end(instance(torsoupposture, torsoupposture10)),
			at_end(instance(armtosideposture, armtosideposture115)),
			at_end(hastorsoposture(torso1, torsoupposture10)),
			at_end(hasarmposture(leftarm1, armtosideposture108)),
			at_end(instance(armtosideposture, armtosideposture108)),
			at_end(on(mug2, placingareaeastrightcounter1)),
			at_end(on(mug1, placingareaeastrightcounter1)),
			%at_end(instance(on, on_1x5)),
			%at_end(instance(on, on_0x5)),
			%at_end(hasphysicalentity(on_0x5, mug1)),
			%at_end(hasarea(on_1x5, placingareaeastrightcounter1)),
			%at_end(hasphysicalentity(on_1x5, mug2)),
			%at_end(hasarea(on_0x5, placingareaeastrightcounter1)),
			at_end(instance(gripperopenedposture, gripperopenedposture15))
		],
		none,				%% failed operation
		race_dummy,			%% failure type
		[
			tuck_arms(leftarm1, rightarm1, armunnamedposture, armunnamedposture, armunnamedposture1, armunnamedposture0, armtuckedposture, armtuckedposture, armtuckedposture7, armtuckedposture13),
			move_base(floorareatamsrestaurant1, premanipulationareasouthtable1),
			move_torso(torso1, torsodownposture, torsodownposture0, torsoupposture, torsoupposture2),
			tuck_arms(leftarm1, rightarm1, armtuckedposture, armtuckedposture, armtuckedposture7, armtuckedposture13, armuntuckedposture, armuntuckedposture, armuntuckedposture17, armuntuckedposture1002),
			move_arm_to_side(leftarm1, armuntuckedposture, armuntuckedposture17, armtosideposture23),
			move_arm_to_side(rightarm1, armcarryposture, armcarryposture43, armtosideposture79),
			move_base_blind_to_ma(premanipulationareasouthtable1, manipulationareasouthtable1),
			pick_up_object(mug1, leftarm1, manipulationareasouthtable1, placingareawestrighttable1, leftgripper1, gripperopeningposture1, gripperholdingposture2, torsoupposture2, armtosideposture23),
			pick_up_object(mug2, rightarm1, manipulationareasouthtable1, placingareawestrighttable1, rightgripper1, gripperopeningposture3, gripperholdingposture4, torsoupposture6, armtosideposture79),
			move_base_blind_to_pma(manipulationareasouthtable1, premanipulationareasouthtable1),
			move_torso(torso1, torsoupposture, torsoupposture2, torsomiddleposture, torsomiddleposture4),
			move_arms_to_carryposture(leftarm1, rightarm1, armtosideposture, armtuckedposture, armtosideposture33, armtuckedposture21, armcarryposture37, armcarryposture43),
			move_base(premanipulationareasouthtable1, premanipulationareaeastcounter1),
			move_torso(torso1, torsomiddleposture, torsomiddleposture8, torsoupposture, torsoupposture10),
			move_arm_to_side(rightarm1, armcarryposture, armcarryposture91, armtosideposture99),
			move_arm_to_side(leftarm1, armcarryposture, armcarryposture97, armtosideposture101),
			move_base_blind_to_ma(premanipulationareaeastcounter1, manipulationareaeastcounter1),
			place_object(mug1, leftarm1, manipulationareaeastcounter1, placingareaeastrightcounter1, leftgripper1, gripperholdingposture2, gripperopeningposture5, torsoupposture10, armtosideposture108),
			place_object(mug2, rightarm1, manipulationareaeastcounter1, placingareaeastrightcounter1, rightgripper1, gripperholdingposture4, gripperopeningposture6, torsoupposture10, armtosideposture115),
			move_base_blind_to_pma(manipulationareaeastcounter1, premanipulationareaeastcounter1)
		]
	]
)).

:- assert(
robot_activity_experience(
	
	1150,					%% episode ID
	clear_table,				%% problem
	[
		clear_table(mug1,mug2,table1,counter1),	%% Task
		[						%% KeyProps
			at_start(instance(armunnamedposture, armunnamedposture0)),
			at_start(instance(gripperclosedposture, gripperclosedposture0)),
			at_start(hasgripperposture(leftgripper1, gripperclosedposture1)),
			at_start(on(mug1, placingareawestrighttable1)),
			at_start(on(mug2, placingareaeastrighttable1)),
			at_start(robotat(trixi1, floorareatamsrestaurant1)),
			%at_start(instance(on, on6)),
			%at_start(hasarea(on5, placingareawestrighttable1)),
			%at_start(instance(on, on5)),
			%at_start(hasphysicalentity(on6, mug2)),
			%at_start(hasarea(on6, placingareaeastrighttable1)),
			%at_start(hasphysicalentity(on5, mug1)),
			%at_start(hasrobot(robotat0, trixi1)),
			%at_start(instance(robotat, robotat0)),
			%at_start(hasarea(robotat0, floorareatamsrestaurant1)),
			at_start(hasarmposture(rightarm1, armunnamedposture0)),
			at_start(hasgripperposture(rightgripper1, gripperclosedposture0)),
			at_start(instance(gripperclosedposture, gripperclosedposture1)),
			at_start(instance(armunnamedposture, armunnamedposture1)),
			at_start(hasarmposture(leftarm1, armunnamedposture1)),
			at_start(instance(torsodownposture, torsodownposture0)),
			at_start(hastorsoposture(torso1, torsodownposture0)),
			throughout(haspremanipulationarea(table1, premanipulationareasouthtable1)),
			throughout(instance(table, table1)),
			throughout(instance(arm, leftarm1)),
			throughout(hasplacingarearight(sittingareawesttable1, placingareawestrighttable1)),
			throughout(instance(placingarea, placingareasouthrighttable2)),
			throughout(hasplacingarea(table2, placingareanorthlefttable2)),
			throughout(hasplacingarea(table1, placingareaeastlefttable1)),
			throughout(hasplacingarearight(sittingareasouthtable2, placingareasouthrighttable2)),
			throughout(hasmanipulationareaeast(table2, manipulationareaeasttable2)),
			throughout(hasmanipulationarea(table1, manipulationareasouthtable1)),
			throughout(instance(placingarea, placingareawestlefttable1)),
			throughout(hasplacingarea(table1, placingareawestlefttable1)),
			throughout(hasmanipulationarea(placingareasouthlefttable2, manipulationareawesttable2)),
			%throughout(instance(on, on2)),
			throughout(instance(manipulationarea, manipulationareanorthtable1)),
			throughout(hasgripper(leftarm1, leftgripper1)),
			throughout(instance(premanipulationarea, premanipulationareaeasttable2)),
			throughout(haspremanipulationarea(table2, premanipulationareawesttable2)),
			throughout(hasmanipulationareawest(table2, manipulationareawesttable2)),
			throughout(hasplacingarea(counter1, placingareaeastrightcounter1)),
			throughout(hasplacingarealeft(sittingareanorthtable2, placingareanorthlefttable2)),
			throughout(hasplacingarea(table2, placingareasouthrighttable2)),
			%throughout(hasarea(on2, nearareatable1)),
			throughout(hassittingarea(table2, sittingareasouthtable2)),
			throughout(haspremanipulationarea(manipulationareasouthtable1, premanipulationareasouthtable1)),
			throughout(instance(premanipulationarea, premanipulationareawesttable2)),
			throughout(hasmanipulationarea(placingareaeastrightcounter1, manipulationareaeastcounter1)),
			throughout(hasmanipulationarea(placingareawestlefttable1, manipulationareanorthtable1)),
			throughout(haspremanipulationarea(table2, premanipulationareaeasttable2)),
			throughout(hasmanipulationarea(placingareaeastlefttable1, manipulationareasouthtable1)),
			throughout(hasplacingarealeft(sittingareawesttable1, placingareawestlefttable1)),
			throughout(hasmanipulationarea(placingareaeastrighttable1, manipulationareanorthtable1)),
			throughout(instance(torso, torso1)),
			throughout(hasplacingarealeft(sittingareasouthtable2, placingareasouthlefttable2)),
			throughout(instance(mug, mug2)),
			throughout(instance(premanipulationarea, premanipulationareanorthtable1)),
			throughout(instance(sittingarea, sittingareanorthtable2)),
			throughout(instance(sittingarea, sittingareasouthtable2)),
			throughout(hasmanipulationarea(placingareawestrighttable1, manipulationareasouthtable1)),
			throughout(instance(placingarea, placingareawestrighttable1)),
			throughout(hasmanipulationarea(counter1, manipulationareaeastcounter1)),
			throughout(instance(mug, mug1)),
			throughout(instance(sittingarea, sittingareawesttable1)),
			%throughout(hasphysicalentity(on2, table1)),
			throughout(hasmanipulationarea(placingareanorthrighttable2, manipulationareawesttable2)),
			throughout(haspremanipulationarea(manipulationareawesttable2, premanipulationareawesttable2)),
			throughout(hasmanipulationareasouth(table1, manipulationareasouthtable1)),
			throughout(hasplacingarea(table1, placingareawestrighttable1)),
			%throughout(hasphysicalentity(on3, table2)),
			throughout(haspremanipulationarea(table1, premanipulationareanorthtable1)),
			throughout(instance(arm, rightarm1)),
			throughout(hasmanipulationarea(table2, manipulationareaeasttable2)),
			throughout(haspremanipulationarea(manipulationareanorthtable1, premanipulationareanorthtable1)),
			throughout(hasplacingarearight(sittingareanorthtable2, placingareanorthrighttable2)),
			throughout(instance(manipulationarea, manipulationareaeasttable2)),
			throughout(instance(table, table2)),
			throughout(instance(placingarea, placingareaeastlefttable1)),
			throughout(haspremanipulationarea(manipulationareaeasttable2, premanipulationareaeasttable2)),
			%throughout(hasphysicalentity(on1, counter1)),
			throughout(hasmanipulationareanorth(table1, manipulationareanorthtable1)),
			throughout(hasplacingarea(table2, placingareanorthrighttable2)),
			throughout(hassittingarea(table1, sittingareawesttable1)),
			throughout(hasplacingarealeft(sittingareaeasttable1, placingareaeastlefttable1)),
			throughout(hasplacingarea(table2, placingareasouthlefttable2)),
			throughout(hasgripper(rightarm1, rightgripper1)),
			throughout(hasplacingarea(table1, placingareaeastrighttable1)),
			throughout(instance(manipulationarea, manipulationareasouthtable1)),
			throughout(instance(gripper, leftgripper1)),
			throughout(hassittingarea(table2, sittingareanorthtable2)),
			throughout(hasmanipulationarea(placingareanorthlefttable2, manipulationareaeasttable2)),
			throughout(hasmanipulationarea(placingareasouthrighttable2, manipulationareaeasttable2)),
			throughout(instance(counter, counter1)),
			throughout(hassittingarea(table1, sittingareaeasttable1)),
			%throughout(instance(on, on3)),
			%throughout(hasarea(on3, nearareatable2)),
			throughout(haspremanipulationarea(manipulationareaeastcounter1, premanipulationareaeastcounter1)),
			throughout(instance(premanipulationarea, premanipulationareasouthtable1)),
			throughout(instance(manipulationarea, manipulationareaeastcounter1)),
			throughout(instance(placingarea, placingareanorthrighttable2)),
			throughout(instance(manipulationarea, manipulationareawesttable2)),
			throughout(instance(placingarea, placingareaeastrightcounter1)),
			throughout(instance(placingarea, placingareanorthlefttable2)),
			throughout(instance(sittingarea, sittingareaeasttable1)),
			throughout(instance(placingarea, placingareaeastrighttable1)),
			throughout(hasmanipulationarea(table2, manipulationareawesttable2)),
			throughout(instance(placingarea, placingareasouthlefttable2)),
			throughout(instance(premanipulationarea, premanipulationareaeastcounter1)),
			throughout(hasplacingarearight(sittingareaeasttable1, placingareaeastrighttable1)),
			throughout(instance(gripper, rightgripper1)),
			%throughout(hasarea(on1, nearareacounter1)),
			throughout(hasmanipulationarea(table1, manipulationareanorthtable1)),
			%throughout(instance(on, on1)),
			at_end(instance(gripperopenedposture, gripperopenedposture12)),
			%at_end(hasrobot(robotat33, trixi1)),
			%at_end(hasarea(robotat33, premanipulationareaeastcounter1)),
			%at_end(instance(robotat, robotat33)),
			at_end(robotat(trixi1, premanipulationareaeastcounter1)),
			at_end(hasgripperposture(rightgripper1, gripperopenedposture15)),
			at_end(hasarmposture(rightarm1, armtosideposture115)),
			at_end(hasgripperposture(leftgripper1, gripperopenedposture12)),
			at_end(instance(torsoupposture, torsoupposture10)),
			at_end(instance(armtosideposture, armtosideposture115)),
			at_end(hastorsoposture(torso1, torsoupposture10)),
			at_end(hasarmposture(leftarm1, armtosideposture108)),
			at_end(instance(armtosideposture, armtosideposture108)),
			at_end(on(mug2, placingareaeastrightcounter1)),
			at_end(on(mug1, placingareaeastrightcounter1)),
			%at_end(instance(on, on_1x5)),
			%at_end(instance(on, on_0x5)),
			%at_end(hasphysicalentity(on_0x5, mug1)),
			%at_end(hasarea(on_1x5, placingareaeastrightcounter1)),
			%at_end(hasphysicalentity(on_1x5, mug2)),
			%at_end(hasarea(on_0x5, placingareaeastrightcounter1)),
			at_end(instance(gripperopenedposture, gripperopenedposture15))
		],
		none,				%% failed operation
		race_dummy,			%% failure type
		[
			tuck_arms(leftarm1, rightarm1, armunnamedposture, armunnamedposture, armunnamedposture1, armunnamedposture0, armtuckedposture, armtuckedposture, armtuckedposture7, armtuckedposture13),
			move_base(floorareatamsrestaurant1, premanipulationareasouthtable1),
			move_torso(torso1, torsodownposture, torsodownposture0, torsoupposture, torsoupposture2),
			tuck_arms(leftarm1, rightarm1, armtuckedposture, armtuckedposture, armtuckedposture7, armtuckedposture13, armuntuckedposture, armuntuckedposture, armuntuckedposture17, armuntuckedposture1002),
			move_arm_to_side(leftarm1, armuntuckedposture, armuntuckedposture17, armtosideposture23),
			move_base_blind_to_ma(premanipulationareasouthtable1, manipulationareasouthtable1),
			pick_up_object(mug1, leftarm1, manipulationareasouthtable1, placingareawestrighttable1, leftgripper1, gripperopeningposture1, gripperholdingposture2, torsoupposture2, armtosideposture23),
			move_base_blind_to_pma(manipulationareasouthtable1, premanipulationareasouthtable1),
			move_torso(torso1, torsoupposture, torsoupposture2, torsomiddleposture, torsomiddleposture4),
			move_arms_to_carryposture(leftarm1, rightarm1, armtosideposture, armtuckedposture, armtosideposture33, armtuckedposture21, armcarryposture37, armcarryposture43),
			move_base(premanipulationareasouthtable1, premanipulationareanorthtable1),
			move_torso(torso1, torsomiddleposture, torsomiddleposture4, torsoupposture, torsoupposture6),
			move_arm_to_side(rightarm1, armcarryposture, armcarryposture43, armtosideposture79),
			move_base_blind_to_ma(premanipulationareanorthtable1, manipulationareanorthtable1),
			pick_up_object(mug2, rightarm1, manipulationareanorthtable1, placingareaeastrighttable1, rightgripper1, gripperopeningposture3, gripperholdingposture4, torsoupposture6, armtosideposture79),
			move_base_blind_to_pma(manipulationareanorthtable1, premanipulationareanorthtable1),
			move_torso(torso1, torsoupposture, torsoupposture6, torsomiddleposture, torsomiddleposture8),
			move_arms_to_carryposture(leftarm1, rightarm1, armcarryposture, armtosideposture, armcarryposture77, armtosideposture85, armcarryposture97, armcarryposture91),
			move_base(premanipulationareanorthtable1, premanipulationareaeastcounter1),
			move_torso(torso1, torsomiddleposture, torsomiddleposture8, torsoupposture, torsoupposture10),
			move_arm_to_side(rightarm1, armcarryposture, armcarryposture91, armtosideposture99),
			move_arm_to_side(leftarm1, armcarryposture, armcarryposture97, armtosideposture101),
			move_base_blind_to_ma(premanipulationareaeastcounter1, manipulationareaeastcounter1),
			place_object(mug1, leftarm1, manipulationareaeastcounter1, placingareaeastrightcounter1, leftgripper1, gripperholdingposture2, gripperopeningposture5, torsoupposture10, armtosideposture108),
			place_object(mug2, rightarm1, manipulationareaeastcounter1, placingareaeastrightcounter1, rightgripper1, gripperholdingposture4, gripperopeningposture6, torsoupposture10, armtosideposture115),
			move_base_blind_to_pma(manipulationareaeastcounter1, premanipulationareaeastcounter1)
		]
	]
)).
:- assert(
robot_activity_experience(
	
	1151,					%% episode ID
	clear_table,				%% problem
	[
		clear_table(mug1,table1,counter1),	%% Task
		[						%% KeyProps
			at_start(instance(armunnamedposture, armunnamedposture0)),
			at_start(instance(gripperclosedposture, gripperclosedposture0)),
			at_start(on(mug1, placingareawestrighttable1)),
			at_start(on(mug2, placingareaeastrighttable1)),
			at_start(robotat(trixi1, floorareatamsrestaurant1)),
			%at_start(instance(on, on6)),
			%at_start(hasarea(on5, placingareawestrighttable1)),
			%at_start(instance(on, on5)),
			%at_start(hasphysicalentity(on6, mug2)),
			%at_start(hasarea(on6, placingareaeastrighttable1)),
			%at_start(hasphysicalentity(on5, mug1)),
			%at_start(hasrobot(robotat0, trixi1)),
			%at_start(instance(robotat, robotat0)),
			%at_start(hasarea(robotat0, floorareatamsrestaurant1)),
			at_start(hasgripperposture(rightgripper1, gripperclosedposture0)),
			at_start(instance(gripperclosedposture, gripperclosedposture1)),
			at_start(instance(armunnamedposture, armunnamedposture1)),
			at_start(hasarmposture(leftarm1, armunnamedposture1)),
			at_start(instance(torsodownposture, torsodownposture0)),
			at_start(hasarmposture(rightarm1, armunnamedposture0)),
			at_start(hasgripperposture(leftgripper1, gripperclosedposture1)),
			at_start(hastorsoposture(torso1, torsodownposture0)),
			throughout(haspremanipulationarea(table1, premanipulationareasouthtable1)),
			throughout(instance(table, table1)),
			throughout(instance(arm, leftarm1)),
			throughout(hasplacingarearight(sittingareawesttable1, placingareawestrighttable1)),
			throughout(instance(placingarea, placingareasouthrighttable2)),
			throughout(hasplacingarea(table2, placingareanorthlefttable2)),
			throughout(hasplacingarea(table1, placingareaeastlefttable1)),
			throughout(hasplacingarearight(sittingareasouthtable2, placingareasouthrighttable2)),
			throughout(hasmanipulationareaeast(table2, manipulationareaeasttable2)),
			throughout(hasmanipulationarea(table1, manipulationareasouthtable1)),
			throughout(instance(placingarea, placingareawestlefttable1)),
			throughout(hasplacingarea(table1, placingareawestlefttable1)),
			throughout(hasmanipulationarea(placingareasouthlefttable2, manipulationareawesttable2)),
			%throughout(instance(on, on2)),
			throughout(instance(manipulationarea, manipulationareanorthtable1)),
			throughout(hasgripper(leftarm1, leftgripper1)),
			throughout(instance(premanipulationarea, premanipulationareaeasttable2)),
			throughout(haspremanipulationarea(table2, premanipulationareawesttable2)),
			throughout(hasmanipulationareawest(table2, manipulationareawesttable2)),
			throughout(hasplacingarea(counter1, placingareaeastrightcounter1)),
			throughout(hasplacingarealeft(sittingareanorthtable2, placingareanorthlefttable2)),
			throughout(hasplacingarea(table2, placingareasouthrighttable2)),
			%throughout(hasarea(on2, nearareatable1)),
			throughout(hassittingarea(table2, sittingareasouthtable2)),
			throughout(haspremanipulationarea(manipulationareasouthtable1, premanipulationareasouthtable1)),
			throughout(instance(premanipulationarea, premanipulationareawesttable2)),
			throughout(hasmanipulationarea(placingareaeastrightcounter1, manipulationareaeastcounter1)),
			throughout(hasmanipulationarea(placingareawestlefttable1, manipulationareanorthtable1)),
			throughout(haspremanipulationarea(table2, premanipulationareaeasttable2)),
			throughout(hasmanipulationarea(placingareaeastlefttable1, manipulationareasouthtable1)),
			throughout(hasplacingarealeft(sittingareawesttable1, placingareawestlefttable1)),
			throughout(hasmanipulationarea(placingareaeastrighttable1, manipulationareanorthtable1)),
			throughout(instance(torso, torso1)),
			throughout(hasplacingarealeft(sittingareasouthtable2, placingareasouthlefttable2)),
			throughout(instance(mug, mug2)),
			throughout(instance(premanipulationarea, premanipulationareanorthtable1)),
			throughout(instance(sittingarea, sittingareanorthtable2)),
			throughout(instance(sittingarea, sittingareasouthtable2)),
			throughout(hasmanipulationarea(placingareawestrighttable1, manipulationareasouthtable1)),
			throughout(instance(placingarea, placingareawestrighttable1)),
			throughout(hasmanipulationarea(counter1, manipulationareaeastcounter1)),
			throughout(instance(mug, mug1)),
			throughout(instance(sittingarea, sittingareawesttable1)),
			%throughout(hasphysicalentity(on2, table1)),
			throughout(hasmanipulationarea(placingareanorthrighttable2, manipulationareawesttable2)),
			throughout(haspremanipulationarea(manipulationareawesttable2, premanipulationareawesttable2)),
			throughout(hasmanipulationareasouth(table1, manipulationareasouthtable1)),
			throughout(hasplacingarea(table1, placingareawestrighttable1)),
			%throughout(hasphysicalentity(on3, table2)),
			throughout(haspremanipulationarea(table1, premanipulationareanorthtable1)),
			throughout(instance(arm, rightarm1)),
			throughout(hasmanipulationarea(table2, manipulationareaeasttable2)),
			throughout(haspremanipulationarea(manipulationareanorthtable1, premanipulationareanorthtable1)),
			throughout(hasplacingarearight(sittingareanorthtable2, placingareanorthrighttable2)),
			throughout(instance(manipulationarea, manipulationareaeasttable2)),
			throughout(instance(table, table2)),
			throughout(instance(placingarea, placingareaeastlefttable1)),
			throughout(haspremanipulationarea(manipulationareaeasttable2, premanipulationareaeasttable2)),
			%throughout(hasphysicalentity(on1, counter1)),
			throughout(hasmanipulationareanorth(table1, manipulationareanorthtable1)),
			throughout(hasplacingarea(table2, placingareanorthrighttable2)),
			throughout(hassittingarea(table1, sittingareawesttable1)),
			throughout(hasplacingarealeft(sittingareaeasttable1, placingareaeastlefttable1)),
			throughout(hasplacingarea(table2, placingareasouthlefttable2)),
			throughout(hasgripper(rightarm1, rightgripper1)),
			throughout(hasplacingarea(table1, placingareaeastrighttable1)),
			throughout(instance(manipulationarea, manipulationareasouthtable1)),
			throughout(instance(gripper, leftgripper1)),
			throughout(hassittingarea(table2, sittingareanorthtable2)),
			throughout(hasmanipulationarea(placingareanorthlefttable2, manipulationareaeasttable2)),
			throughout(hasmanipulationarea(placingareasouthrighttable2, manipulationareaeasttable2)),
			throughout(instance(counter, counter1)),
			throughout(hassittingarea(table1, sittingareaeasttable1)),
			%throughout(instance(on, on3)),
			%throughout(hasarea(on3, nearareatable2)),
			throughout(haspremanipulationarea(manipulationareaeastcounter1, premanipulationareaeastcounter1)),
			throughout(instance(premanipulationarea, premanipulationareasouthtable1)),
			throughout(instance(manipulationarea, manipulationareaeastcounter1)),
			throughout(instance(placingarea, placingareanorthrighttable2)),
			throughout(instance(manipulationarea, manipulationareawesttable2)),
			throughout(instance(placingarea, placingareaeastrightcounter1)),
			throughout(instance(placingarea, placingareanorthlefttable2)),
			throughout(instance(sittingarea, sittingareaeasttable1)),
			throughout(instance(placingarea, placingareaeastrighttable1)),
			throughout(hasmanipulationarea(table2, manipulationareawesttable2)),
			throughout(instance(placingarea, placingareasouthlefttable2)),
			throughout(instance(premanipulationarea, premanipulationareaeastcounter1)),
			throughout(hasplacingarearight(sittingareaeasttable1, placingareaeastrighttable1)),
			throughout(instance(gripper, rightgripper1)),
			%throughout(hasarea(on1, nearareacounter1)),
			throughout(hasmanipulationarea(table1, manipulationareanorthtable1)),
			%throughout(instance(on, on1)),
			at_end(instance(gripperopenedposture, gripperopenedposture12)),
			%at_end(hasrobot(robotat33, trixi1)),
			%at_end(hasarea(robotat33, premanipulationareaeastcounter1)),
			%at_end(instance(robotat, robotat33)),
			at_end(robotat(trixi1, premanipulationareaeastcounter1)),
			at_end(hasgripperposture(rightgripper1, gripperopenedposture15)),
			at_end(hasarmposture(rightarm1, armtosideposture115)),
			at_end(hasgripperposture(leftgripper1, gripperopenedposture12)),
			at_end(instance(torsoupposture, torsoupposture10)),
			at_end(instance(armtosideposture, armtosideposture115)),
			at_end(hastorsoposture(torso1, torsoupposture10)),
			at_end(hasarmposture(leftarm1, armtosideposture101)),
			at_end(instance(armtosideposture, armtosideposture101)),
			%at_end(instance(on, on_1x5)),
			%at_end(instance(on, on_0x5)),
			%at_end(hasphysicalentity(on_0x5, mug1)),
			%at_end(hasarea(on_1x5, placingareaeastrightcounter1)),
			%at_end(hasphysicalentity(on_1x5, mug2)),
			%at_end(hasarea(on_0x5, placingareaeastrightcounter1)),
			at_end(on(mug2, placingareaeastrightcounter1)),
			at_end(on(mug1, placingareaeastrightcounter1)),
			at_end(instance(gripperopenedposture, gripperopenedposture15))
		],
		none,				%% failed operation
		race_dummy,			%% failure type
		[
			tuck_arms(leftarm1, rightarm1, armunnamedposture, armunnamedposture, armunnamedposture1, armunnamedposture0, armtuckedposture, armtuckedposture, armtuckedposture7, armtuckedposture13),
			move_base(floorareatamsrestaurant1, premanipulationareasouthtable1),
			move_torso(torso1, torsodownposture, torsodownposture0, torsoupposture, torsoupposture2),
			tuck_arms(leftarm1, rightarm1, armtuckedposture, armtuckedposture, armtuckedposture7, armtuckedposture13, armuntuckedposture, armuntuckedposture, armuntuckedposture17, armuntuckedposture1002),
			move_arm_to_side(leftarm1, armuntuckedposture, armuntuckedposture17, armtosideposture23),
			move_base_blind_to_ma(premanipulationareasouthtable1, manipulationareasouthtable1),
			pick_up_object(mug1, leftarm1, manipulationareasouthtable1, placingareawestrighttable1, leftgripper1, gripperopeningposture1, gripperholdingposture2, torsoupposture2, armtosideposture23),
			move_base_blind_to_pma(manipulationareasouthtable1, premanipulationareasouthtable1),
			move_torso(torso1, torsoupposture, torsoupposture6, torsomiddleposture, torsomiddleposture8),
			move_arms_to_carryposture(leftarm1, rightarm1, armcarryposture, armtosideposture,armcarryposture77, armtosideposture85, armcarryposture97, armcarryposture91),
			move_base(premanipulationareasouthtable1, premanipulationareaeastcounter1),
			move_torso(torso1, torsomiddleposture, torsomiddleposture8, torsoupposture, torsoupposture10),
			move_arm_to_side(leftarm1, armcarryposture, armcarryposture97, armtosideposture101),
			move_base_blind_to_ma(premanipulationareaeastcounter1, manipulationareaeastcounter1),
			place_object(mug1, leftarm1, manipulationareaeastcounter1, placingareaeastrightcounter1, leftgripper1, gripperholdingposture2, gripperopeningposture3, torsoupposture10, armtosideposture101),
			move_base_blind_to_pma(manipulationareaeastcounter1, premanipulationareaeastcounter1)
		]
	]
)).

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
:- assert(
robot_activity_experience(
	
	9576,					%% episode ID
	grasp_object_w_arm,				%% problem
	[
		grasp_object_w_arm(mug1,rightarm1),	%% Task
		[						%% KeyProps
			at_start(instance(armunnamedposture, armunnamedposture0)),
			at_start(hasphysicalentity(on4, mug1)),
			at_start(instance(gripperclosedposture, gripperclosedposture0)),
			at_start(hasrobot(robotat0, trixi1)),
			at_start(hasgripperposture(rightgripper1, gripperclosedposture0)),
			at_start(instance(armunnamedposture, armunnamedposture1)),
			at_start(instance(robotat, robotat0)),
			at_start(hasarea(on4, placingareaeastrightcounter1)),
			at_start(hastorsoposture(torso1, torsodownposture0)),
			at_start(hasarmposture(leftarm1, armunnamedposture0)),
			at_start(instance(on, on4)),
			at_start(hasarea(robotat0, floorareatamsrestaurant1)),
			at_start(hasarmposture(rightarm1, armunnamedposture1)),
			at_start(instance(torsodownposture, torsodownposture0)),
			throughout(haspremanipulationarea(table1, premanipulationareasouthtable1)),
			throughout(instance(table, table1)),
			throughout(instance(arm, leftarm1)),
			throughout(hasplacingarearight(sittingareawesttable1, placingareawestrighttable1)),
			throughout(instance(placingarea, placingareasouthrighttable2)),
			throughout(hasplacingarea(table2, placingareanorthlefttable2)),
			throughout(hasplacingarea(table1, placingareaeastlefttable1)),
			throughout(haspremanipulationarea(manipulationareaeastcounter1, premanipulationareaeastcounter1)),
			throughout(hasmanipulationarea(table1, manipulationareasouthtable1)),
			throughout(instance(placingarea, placingareawestlefttable1)),
			throughout(hasplacingarea(table1, placingareawestlefttable1)),
			throughout(hasmanipulationarea(placingareasouthlefttable2, manipulationareawesttable2)),
			throughout(instance(on, on2)),
			throughout(instance(manipulationarea, manipulationareanorthtable1)),
			throughout(hasgripper(leftarm1, leftgripper1)),
			throughout(instance(premanipulationarea, premanipulationareaeasttable2)),
			throughout(haspremanipulationarea(table2, premanipulationareawesttable2)),
			throughout(hasmanipulationareawest(table2, manipulationareawesttable2)),
			throughout(hasplacingarea(counter1, placingareaeastrightcounter1)),
			throughout(at(guest1, sittingareawesttable1)),
			throughout(hasplacingarea(table2, placingareasouthrighttable2)),
			throughout(hasarea(on2, nearareatable1)),
			throughout(hassittingarea(table2, sittingareasouthtable2)),
			throughout(haspremanipulationarea(manipulationareasouthtable1, premanipulationareasouthtable1)),
			throughout(instance(premanipulationarea, premanipulationareawesttable2)),
			throughout(hasmanipulationarea(placingareaeastrightcounter1, manipulationareaeastcounter1)),
			throughout(hasmanipulationarea(placingareawestlefttable1, manipulationareanorthtable1)),
			throughout(haspremanipulationarea(table2, premanipulationareaeasttable2)),
			throughout(hasmanipulationarea(placingareaeastlefttable1, manipulationareasouthtable1)),
			throughout(instance(guest, guest1)),
			throughout(hasplacingarearight(sittingareasouthtable2, placingareasouthrighttable2)),
			throughout(hasmanipulationarea(placingareaeastrighttable1, manipulationareanorthtable1)),
			throughout(instance(torso, torso1)),
			throughout(instance(premanipulationarea, premanipulationareanorthtable1)),
			throughout(instance(sittingarea, sittingareanorthtable2)),
			throughout(instance(sittingarea, sittingareasouthtable2)),
			throughout(hasmanipulationarea(placingareawestrighttable1, manipulationareasouthtable1)),
			throughout(instance(placingarea, placingareawestrighttable1)),
			throughout(hasmanipulationarea(counter1, manipulationareaeastcounter1)),
			throughout(instance(mug, mug1)),
			throughout(instance(sittingarea, sittingareawesttable1)),
			throughout(instance(armtuckedposture, dummyarmtuckedposture)),
			throughout(hasphysicalentity(at1, guest1)),
			throughout(hasphysicalentity(on2, table1)),
			throughout(hasmanipulationarea(placingareanorthrighttable2, manipulationareawesttable2)),
			throughout(haspremanipulationarea(manipulationareawesttable2, premanipulationareawesttable2)),
			throughout(hasmanipulationareasouth(table1, manipulationareasouthtable1)),
			throughout(hasplacingarea(table1, placingareawestrighttable1)),
			throughout(hasphysicalentity(on3, table2)),
			throughout(haspremanipulationarea(table1, premanipulationareanorthtable1)),
			throughout(instance(arm, rightarm1)),
			throughout(hasmanipulationarea(table2, manipulationareaeasttable2)),
			throughout(haspremanipulationarea(manipulationareanorthtable1, premanipulationareanorthtable1)),
			throughout(hasplacingarearight(sittingareanorthtable2, placingareanorthrighttable2)),
			throughout(instance(gripperclosedposture, gripperclosedposture1)),
			throughout(instance(manipulationarea, manipulationareaeasttable2)),
			throughout(instance(table, table2)),
			throughout(instance(placingarea, placingareaeastlefttable1)),
			throughout(haspremanipulationarea(manipulationareaeasttable2, premanipulationareaeasttable2)),
			throughout(hasphysicalentity(on1, counter1)),
			throughout(hasmanipulationareanorth(table1, manipulationareanorthtable1)),
			throughout(hasplacingarea(table2, placingareanorthrighttable2)),
			throughout(hassittingarea(table1, sittingareawesttable1)),
			throughout(instance(placingarea, placingareaeastrightcounter1)),
			throughout(hasarea(at1, sittingareawesttable1)),
			throughout(hasplacingarea(table2, placingareasouthlefttable2)),
			throughout(hasgripper(rightarm1, rightgripper1)),
			throughout(hasplacingarea(table1, placingareaeastrighttable1)),
			throughout(instance(manipulationarea, manipulationareasouthtable1)),
			throughout(instance(gripper, leftgripper1)),
			throughout(hassittingarea(table2, sittingareanorthtable2)),
			throughout(hasmanipulationarea(placingareanorthlefttable2, manipulationareaeasttable2)),
			throughout(hasmanipulationarea(placingareasouthrighttable2, manipulationareaeasttable2)),
			throughout(instance(counter, counter1)),
			throughout(hassittingarea(table1, sittingareaeasttable1)),
			throughout(instance(on, on3)),
			throughout(hasarea(on3, nearareatable2)),
			throughout(hasmanipulationareaeast(table2, manipulationareaeasttable2)),
			throughout(hasgripperposture(leftgripper1, gripperclosedposture1)),
			throughout(instance(premanipulationarea, premanipulationareasouthtable1)),
			throughout(instance(manipulationarea, manipulationareaeastcounter1)),
			throughout(instance(placingarea, placingareanorthrighttable2)),
			throughout(instance(manipulationarea, manipulationareawesttable2)),
			throughout(instance(placingarea, placingareanorthlefttable2)),
			throughout(instance(sittingarea, sittingareaeasttable1)),
			throughout(instance(placingarea, placingareaeastrighttable1)),
			throughout(instance(at, at1)),
			throughout(hasmanipulationarea(table2, manipulationareawesttable2)),
			throughout(instance(placingarea, placingareasouthlefttable2)),
			throughout(instance(premanipulationarea, premanipulationareaeastcounter1)),
			throughout(hasplacingarearight(sittingareaeasttable1, placingareaeastrighttable1)),
			throughout(instance(gripper, rightgripper1)),
			throughout(hasarea(on1, nearareacounter1)),
			throughout(hasmanipulationarea(table1, manipulationareanorthtable1)),
			throughout(instance(on, on1)),
			at_end(haspassiveobject(holding_0x1, mug1)),
			at_end(hastorsoposture(torso1, torsoupposture2)),
			at_end(hasgripperposture(rightgripper1, gripperholdingposture4)),
			at_end(instance(armtuckedposture, armtuckedposture7)),
			at_end(hasgripper(holding_0x1, rightgripper1)),
			at_end(hasarmposture(leftarm1, armtuckedposture7)),
			at_end(instance(torsoupposture, dummytorsoupposture)),
			at_end(instance(torsoupposture, torsoupposture2)),
			at_end(instance(armtosideposture, armtosideposture25)),
			at_end(instance(holding, holding_0x1)),
			at_end(hasarmposture(rightarm1, armtosideposture25)),
			at_end(instance(armuntuckedposture, dummyarmuntuckedposture)),
			at_end(instance(robotat, robotat9)),
			at_end(instance(gripperholdingposture, gripperholdingposture4)),
			at_end(hasarea(robotat9, manipulationareaeastcounter1)),
			at_end(hasrobot(robotat9, trixi1))
		],
		none,				%% failed operation
		race_dummy,			%% failure type
		[
			tuck_arms(armunnamedposture, armunnamedposture, armunnamedposture0, armunnamedposture1, armtuckedposture, armtuckedposture, armtuckedposture7, armtuckedposture13),
			move_base(robotat0, floorareatamsrestaurant1, robotat7, premanipulationareaeastcounter1),
			move_torso(torso1, torsodownposture, torsodownposture0, torsoupposture, torsoupposture2),
			tuck_arms(armtuckedposture, armtuckedposture, armtuckedposture7, armtuckedposture13, armuntuckedposture, armuntuckedposture, armuntuckedposture1002, armuntuckedposture17),
			move_arm_to_side(rightarm1, armuntuckedposture, armuntuckedposture17, armtosideposture19),
			move_base_blind_to_ma(robotat7, premanipulationareaeastcounter1, robotat1003, manipulationareaeastcounter1),
			pick_up_object(mug1, rightarm1, on4, robotat1003_0, manipulationareaeastcounter1, placingareaeastrightcounter1, rightgripper1, holding_0x1, torsoupposture2, armtosideposture19, armtosideposture25)
		]
	]
)).

:- assert(
robot_activity_experience(
	
	4560,					%% episode ID
	grasp_object_w_arm,				%% problem
	[
		grasp_object_w_arm(mug1,rightarm1,counter1),	%% Task
		[						%% KeyProps
			at_start(hasphysicalentity(on4, mug1)),
			at_start(instance(gripperclosedposture, gripperclosedposture0)),
			at_start(instance(robotat, robotat3)),
			at_start(hasarmposture(rightarm1, armtuckedposture15)),
			at_start(hasgripperposture(rightgripper1, gripperclosedposture0)),
			at_start(hastorsoposture(torso1, torsodownposture4)),
			at_start(hasrobot(robotat3, trixi1)),
			at_start(instance(torsodownposture, torsodownposture4)),
			at_start(hasarea(robotat3, premanipulationareaeastcounter1)),
			at_start(hasarea(on4, placingareaeastrightcounter1)),
			at_start(instance(on, on4)),
			at_start(instance(armtuckedposture, armtuckedposture15)),
			throughout(haspremanipulationarea(table1, premanipulationareasouthtable1)),
			throughout(instance(table, table1)),
			throughout(instance(arm, leftarm1)),
			throughout(hasplacingarearight(sittingareawesttable1, placingareawestrighttable1)),
			throughout(instance(placingarea, placingareasouthrighttable2)),
			throughout(hasplacingarea(table2, placingareanorthlefttable2)),
			throughout(hasplacingarea(table1, placingareaeastlefttable1)),
			throughout(hasplacingarearight(sittingareasouthtable2, placingareasouthrighttable2)),
			throughout(haspremanipulationarea(manipulationareaeastcounter1, premanipulationareaeastcounter1)),
			throughout(hasmanipulationarea(table1, manipulationareasouthtable1)),
			throughout(hasarmposture(leftarm1, armtuckedposture7)),
			throughout(instance(floorarea, floorareatamsrestaurant1)),
			throughout(instance(placingarea, placingareawestlefttable1)),
			throughout(hasplacingarea(table1, placingareawestlefttable1)),
			throughout(hasmanipulationarea(placingareasouthlefttable2, manipulationareawesttable2)),
			throughout(instance(on, on2)),
			throughout(instance(manipulationarea, manipulationareanorthtable1)),
			throughout(hasgripper(leftarm1, leftgripper1)),
			throughout(instance(torsoupposture, dummytorsoupposture)),
			throughout(instance(premanipulationarea, premanipulationareaeasttable2)),
			throughout(haspremanipulationarea(table2, premanipulationareawesttable2)),
			throughout(hasmanipulationareawest(table2, manipulationareawesttable2)),
			throughout(hasplacingarea(counter1, placingareaeastrightcounter1)),
			throughout(at(guest1, sittingareawesttable1)),
			throughout(hasplacingarealeft(sittingareanorthtable2, placingareanorthlefttable2)),
			throughout(hasplacingarea(table2, placingareasouthrighttable2)),
			throughout(hasarea(on2, nearareatable1)),
			throughout(hassittingarea(table2, sittingareasouthtable2)),
			throughout(haspremanipulationarea(manipulationareasouthtable1, premanipulationareasouthtable1)),
			throughout(instance(premanipulationarea, premanipulationareawesttable2)),
			throughout(hasmanipulationarea(placingareaeastrightcounter1, manipulationareaeastcounter1)),
			throughout(hasmanipulationarea(placingareawestlefttable1, manipulationareanorthtable1)),
			throughout(haspremanipulationarea(table2, premanipulationareaeasttable2)),
			throughout(hasmanipulationarea(placingareaeastlefttable1, manipulationareasouthtable1)),
			throughout(instance(guest, guest1)),
			throughout(hasplacingarealeft(sittingareawesttable1, placingareawestlefttable1)),
			throughout(hasmanipulationarea(placingareaeastrighttable1, manipulationareanorthtable1)),
			throughout(instance(torso, torso1)),
			throughout(hasplacingarealeft(sittingareasouthtable2, placingareasouthlefttable2)),
			throughout(instance(premanipulationarea, premanipulationareanorthtable1)),
			throughout(instance(sittingarea, sittingareanorthtable2)),
			throughout(instance(sittingarea, sittingareasouthtable2)),
			throughout(hasmanipulationarea(placingareawestrighttable1, manipulationareasouthtable1)),
			throughout(instance(placingarea, placingareawestrighttable1)),
			throughout(hasmanipulationarea(counter1, manipulationareaeastcounter1)),
			throughout(instance(mug, mug1)),
			throughout(instance(sittingarea, sittingareawesttable1)),
			throughout(instance(armtuckedposture, dummyarmtuckedposture)),
			throughout(hasphysicalentity(at1, guest1)),
			throughout(hasphysicalentity(on2, table1)),
			throughout(hasmanipulationarea(placingareanorthrighttable2, manipulationareawesttable2)),
			throughout(haspremanipulationarea(manipulationareawesttable2, premanipulationareawesttable2)),
			throughout(hasmanipulationareasouth(table1, manipulationareasouthtable1)),
			throughout(hasplacingarea(table1, placingareawestrighttable1)),
			throughout(hasphysicalentity(on3, table2)),
			throughout(haspremanipulationarea(table1, premanipulationareanorthtable1)),
			throughout(instance(arm, rightarm1)),
			throughout(hasmanipulationarea(table2, manipulationareaeasttable2)),
			throughout(haspremanipulationarea(manipulationareanorthtable1, premanipulationareanorthtable1)),
			throughout(hasplacingarearight(sittingareanorthtable2, placingareanorthrighttable2)),
			throughout(instance(gripperclosedposture, gripperclosedposture1)),
			throughout(instance(manipulationarea, manipulationareaeasttable2)),
			throughout(instance(table, table2)),
			throughout(instance(placingarea, placingareaeastlefttable1)),
			throughout(haspremanipulationarea(manipulationareaeasttable2, premanipulationareaeasttable2)),
			throughout(hasphysicalentity(on1, counter1)),
			throughout(hasmanipulationareanorth(table1, manipulationareanorthtable1)),
			throughout(hasplacingarea(table2, placingareanorthrighttable2)),
			throughout(hassittingarea(table1, sittingareawesttable1)),
			throughout(hasplacingarealeft(sittingareaeasttable1, placingareaeastlefttable1)),
			throughout(hasarea(at1, sittingareawesttable1)),
			throughout(hasplacingarea(table2, placingareasouthlefttable2)),
			throughout(hasgripper(rightarm1, rightgripper1)),
			throughout(hasplacingarea(table1, placingareaeastrighttable1)),
			throughout(instance(manipulationarea, manipulationareasouthtable1)),
			throughout(instance(gripper, leftgripper1)),
			throughout(hassittingarea(table2, sittingareanorthtable2)),
			throughout(hasmanipulationarea(placingareanorthlefttable2, manipulationareaeasttable2)),
			throughout(hasmanipulationarea(placingareasouthrighttable2, manipulationareaeasttable2)),
			throughout(instance(counter, counter1)),
			throughout(hassittingarea(table1, sittingareaeasttable1)),
			throughout(instance(on, on3)),
			throughout(hasarea(on3, nearareatable2)),
			throughout(hasmanipulationareaeast(table2, manipulationareaeasttable2)),
			throughout(instance(armuntuckedposture, dummyarmuntuckedposture)),
			throughout(hasgripperposture(leftgripper1, gripperclosedposture1)),
			throughout(instance(premanipulationarea, premanipulationareasouthtable1)),
			throughout(instance(manipulationarea, manipulationareaeastcounter1)),
			throughout(instance(placingarea, placingareanorthrighttable2)),
			throughout(instance(manipulationarea, manipulationareawesttable2)),
			throughout(instance(placingarea, placingareaeastrightcounter1)),
			throughout(instance(placingarea, placingareanorthlefttable2)),
			throughout(instance(sittingarea, sittingareaeasttable1)),
			throughout(instance(placingarea, placingareaeastrighttable1)),
			throughout(instance(at, at1)),
			throughout(hasmanipulationarea(table2, manipulationareawesttable2)),
			throughout(instance(placingarea, placingareasouthlefttable2)),
			throughout(instance(premanipulationarea, premanipulationareaeastcounter1)),
			throughout(hasplacingarearight(sittingareaeasttable1, placingareaeastrighttable1)),
			throughout(instance(gripper, rightgripper1)),
			throughout(hasarea(on1, nearareacounter1)),
			throughout(hasmanipulationarea(table1, manipulationareanorthtable1)),
			throughout(instance(on, on1)),
			throughout(instance(armtuckedposture, armtuckedposture7)),
			at_end(instance(torsoupposture, torsoupposture6)),
			at_end(haspassiveobject(holding_0x1, mug1)),
			at_end(instance(armtosideposture, armtosideposture29)),
			at_end(hasarmposture(rightarm1, armtosideposture29)),
			at_end(hasgripperposture(rightgripper1, gripperholdingposture6)),
			at_end(hasgripper(holding_0x1, rightgripper1)),
			at_end(hasarea(robotat5, manipulationareaeastcounter1)),
			at_end(hasrobot(robotat5, trixi1)),
			at_end(hastorsoposture(torso1, torsoupposture6)),
			at_end(instance(gripperholdingposture, gripperholdingposture6)),
			at_end(instance(robotat, robotat5)),
			at_end(instance(holding, holding_0x1))
		],
		none,				%% failed operation
		race_dummy,			%% failure type
		[
			move_torso(torso1, torsodownposture, torsodownposture4, torsoupposture, torsoupposture6),
			tuck_arms(armtuckedposture, armtuckedposture, armtuckedposture7, armtuckedposture15, armuntuckedposture, armuntuckedposture, armuntuckedposture1001, armuntuckedposture19),
			move_arm_to_side(rightarm1, armuntuckedposture, armuntuckedposture19, armtosideposture21),
			move_base_blind_to_ma(robotat3, premanipulationareaeastcounter1, robotat1002, manipulationareaeastcounter1),
			pick_up_object(mug1, rightarm1, on4, robotat1003_0, manipulationareaeastcounter1, placingareaeastrightcounter1, rightgripper1, holding_0x1, torsoupposture6, armtosideposture21, armtosideposture29)
		]
	]
)).

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
:- assert(
robot_activity_experience(
	
	9530,					%% episode ID
	drive_robot,				%% problem
	[
		drive_robot(premanipulationareaeastcounter1),	%% Task
		[						%% KeyProps
			at_start(instance(armunnamedposture, armunnamedposture0)),
			at_start(hasrobot(robotat0, trixi1)),
			at_start(instance(armunnamedposture, armunnamedposture1)),
			at_start(instance(robotat, robotat0)),
			at_start(hasarea(robotat0, floorareatamsrestaurant1)),
			at_start(hasarmposture(leftarm1, armunnamedposture1)),
			at_start(hasarmposture(rightarm1, armunnamedposture0)),
			throughout(haspremanipulationarea(table1, premanipulationareasouthtable1)),
			throughout(instance(table, table1)),
			throughout(instance(gripperclosedposture, gripperclosedposture0)),
			throughout(hasplacingarearight(sittingareawesttable1, placingareawestrighttable1)),
			throughout(instance(placingarea, placingareasouthrighttable2)),
			throughout(hasplacingarea(table2, placingareanorthlefttable2)),
			throughout(hasplacingarea(table1, placingareaeastlefttable1)),
			throughout(hasplacingarearight(sittingareasouthtable2, placingareasouthrighttable2)),
			throughout(haspremanipulationarea(manipulationareaeastcounter1, premanipulationareaeastcounter1)),
			throughout(hasmanipulationarea(table1, manipulationareasouthtable1)),
			throughout(instance(placingarea, placingareawestlefttable1)),
			throughout(hasplacingarea(table1, placingareawestlefttable1)),
			throughout(hasmanipulationarea(placingareasouthlefttable2, manipulationareawesttable2)),
			throughout(instance(on, on2)),
			throughout(instance(manipulationarea, manipulationareanorthtable1)),
			throughout(hasgripper(leftarm1, leftgripper1)),
			throughout(instance(premanipulationarea, premanipulationareaeasttable2)),
			throughout(haspremanipulationarea(table2, premanipulationareawesttable2)),
			throughout(hasmanipulationareawest(table2, manipulationareawesttable2)),
			throughout(hasplacingarea(counter1, placingareaeastrightcounter1)),
			throughout(at(guest1, sittingareawesttable1)),
			throughout(hasplacingarealeft(sittingareanorthtable2, placingareanorthlefttable2)),
			throughout(hasplacingarea(table2, placingareasouthrighttable2)),
			throughout(hasarea(on2, nearareatable1)),
			throughout(hasphysicalentity(on4, mug1)),
			throughout(hassittingarea(table2, sittingareasouthtable2)),
			throughout(hasarea(on4, placingareaeastrightcounter1)),
			throughout(haspremanipulationarea(manipulationareasouthtable1, premanipulationareasouthtable1)),
			throughout(instance(premanipulationarea, premanipulationareawesttable2)),
			throughout(hasgripperposture(leftgripper1, gripperclosedposture0)),
			throughout(hasmanipulationarea(placingareaeastrightcounter1, manipulationareaeastcounter1)),
			throughout(hasmanipulationarea(placingareawestlefttable1, manipulationareanorthtable1)),
			throughout(haspremanipulationarea(table2, premanipulationareaeasttable2)),
			throughout(hasmanipulationarea(placingareaeastlefttable1, manipulationareasouthtable1)),
			throughout(instance(guest, guest1)),
			throughout(hasplacingarealeft(sittingareawesttable1, placingareawestlefttable1)),
			throughout(hasmanipulationarea(placingareaeastrighttable1, manipulationareanorthtable1)),
			throughout(instance(torso, torso1)),
			throughout(hasplacingarealeft(sittingareasouthtable2, placingareasouthlefttable2)),
			throughout(instance(premanipulationarea, premanipulationareanorthtable1)),
			throughout(instance(arm, leftarm1)),
			throughout(instance(sittingarea, sittingareanorthtable2)),
			throughout(instance(sittingarea, sittingareasouthtable2)),
			throughout(hasmanipulationarea(placingareawestrighttable1, manipulationareasouthtable1)),
			throughout(instance(placingarea, placingareawestrighttable1)),
			throughout(hasmanipulationarea(counter1, manipulationareaeastcounter1)),
			throughout(instance(mug, mug1)),
			throughout(instance(sittingarea, sittingareawesttable1)),
			throughout(instance(torsodownposture, torsodownposture0)),
			throughout(hasphysicalentity(at1, guest1)),
			throughout(hasphysicalentity(on2, table1)),
			throughout(hasmanipulationarea(placingareanorthrighttable2, manipulationareawesttable2)),
			throughout(haspremanipulationarea(manipulationareawesttable2, premanipulationareawesttable2)),
			throughout(hasmanipulationareasouth(table1, manipulationareasouthtable1)),
			throughout(hasplacingarea(table1, placingareawestrighttable1)),
			throughout(hasphysicalentity(on3, table2)),
			throughout(haspremanipulationarea(table1, premanipulationareanorthtable1)),
			throughout(instance(arm, rightarm1)),
			throughout(hasmanipulationarea(table2, manipulationareaeasttable2)),
			throughout(haspremanipulationarea(manipulationareanorthtable1, premanipulationareanorthtable1)),
			throughout(hasplacingarearight(sittingareanorthtable2, placingareanorthrighttable2)),
			throughout(instance(gripperclosedposture, gripperclosedposture1)),
			throughout(instance(manipulationarea, manipulationareaeasttable2)),
			throughout(instance(table, table2)),
			throughout(instance(placingarea, placingareaeastlefttable1)),
			throughout(haspremanipulationarea(manipulationareaeasttable2, premanipulationareaeasttable2)),
			throughout(hasphysicalentity(on1, counter1)),
			throughout(hasmanipulationareanorth(table1, manipulationareanorthtable1)),
			throughout(hastorsoposture(torso1, torsodownposture0)),
			throughout(hasplacingarea(table2, placingareanorthrighttable2)),
			throughout(hassittingarea(table1, sittingareawesttable1)),
			throughout(hasplacingarealeft(sittingareaeasttable1, placingareaeastlefttable1)),
			throughout(hasarea(at1, sittingareawesttable1)),
			throughout(hasplacingarea(table2, placingareasouthlefttable2)),
			throughout(hasgripper(rightarm1, rightgripper1)),
			throughout(hasplacingarea(table1, placingareaeastrighttable1)),
			throughout(instance(manipulationarea, manipulationareasouthtable1)),
			throughout(instance(gripper, leftgripper1)),
			throughout(hassittingarea(table2, sittingareanorthtable2)),
			throughout(hasmanipulationarea(placingareanorthlefttable2, manipulationareaeasttable2)),
			throughout(hasmanipulationarea(placingareasouthrighttable2, manipulationareaeasttable2)),
			throughout(instance(counter, counter1)),
			throughout(hassittingarea(table1, sittingareaeasttable1)),
			throughout(instance(on, on3)),
			throughout(hasarea(on3, nearareatable2)),
			throughout(hasmanipulationareaeast(table2, manipulationareaeasttable2)),
			throughout(instance(on, on4)),
			throughout(instance(premanipulationarea, premanipulationareasouthtable1)),
			throughout(instance(manipulationarea, manipulationareaeastcounter1)),
			throughout(instance(placingarea, placingareanorthrighttable2)),
			throughout(hasgripperposture(rightgripper1, gripperclosedposture1)),
			throughout(instance(manipulationarea, manipulationareawesttable2)),
			throughout(instance(placingarea, placingareaeastrightcounter1)),
			throughout(instance(placingarea, placingareanorthlefttable2)),
			throughout(instance(sittingarea, sittingareaeasttable1)),
			throughout(instance(placingarea, placingareaeastrighttable1)),
			throughout(instance(at, at1)),
			throughout(hasmanipulationarea(table2, manipulationareawesttable2)),
			throughout(instance(placingarea, placingareasouthlefttable2)),
			throughout(instance(premanipulationarea, premanipulationareaeastcounter1)),
			throughout(hasplacingarearight(sittingareaeasttable1, placingareaeastrighttable1)),
			throughout(instance(gripper, rightgripper1)),
			throughout(hasarea(on1, nearareacounter1)),
			throughout(hasmanipulationarea(table1, manipulationareanorthtable1)),
			throughout(instance(on, on1)),
			throughout(instance(armtuckedposture, dummyarmtuckedposture)),
			at_end(instance(robotat, robotat7)),
			at_end(hasarea(robotat7, premanipulationareaeastcounter1)),
			at_end(instance(armtuckedposture, armtuckedposture7)),
			at_end(hasarmposture(leftarm1, armtuckedposture7)),
			at_end(instance(armtuckedposture, armtuckedposture13)),
			at_end(hasrobot(robotat7, trixi1)),
			at_end(hasarmposture(rightarm1, armtuckedposture13))
		],
		none,				%% failed operation
		race_dummy,			%% failure type
		[
			tuck_arms(armunnamedposture, armunnamedposture, armunnamedposture1, armunnamedposture0, armtuckedposture, armtuckedposture, armtuckedposture7, armtuckedposture13),
			move_base(robotat0, floorareatamsrestaurant1, robotat7, premanipulationareaeastcounter1)
		]
	]
)).

