(define (problem roverprob200) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 - Rover
	rover0store - Store
	waypoint0 waypoint1 waypoint2 - Waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 camera6 - Camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 objective8 objective9 objective10 objective11 objective12 objective13 objective14 objective15 objective16 objective17 objective18 objective19 objective20 objective21 objective22 objective23 objective24 objective25 objective26 objective27 objective28 - Objective
	)
(:init
	(visible waypoint0 waypoint1)
	(visible waypoint1 waypoint0)
	(visible waypoint0 waypoint2)
	(visible waypoint2 waypoint0)
	(visible waypoint2 waypoint1)
	(visible waypoint1 waypoint2)
	(at_soil_sample waypoint0)
	(at_soil_sample waypoint1)
	(at_soil_sample waypoint2)
	(at_rock_sample waypoint2)
	(at_lander general waypoint0)
	(channel_free general)
	(at rover0 waypoint2)
	(available rover0)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_soil_analysis rover0)
	(equipped_for_rock_analysis rover0)
	(equipped_for_imaging rover0)
	(can_traverse rover0 waypoint2 waypoint0)
	(can_traverse rover0 waypoint0 waypoint2)
	(on_board camera0 rover0)
	(calibration_target camera0 objective9)
	(supports camera0 colour)
	(supports camera0 low_res)
	(on_board camera1 rover0)
	(calibration_target camera1 objective4)
	(supports camera1 colour)
	(supports camera1 high_res)
	(on_board camera2 rover0)
	(calibration_target camera2 objective27)
	(supports camera2 colour)
	(on_board camera3 rover0)
	(calibration_target camera3 objective21)
	(supports camera3 high_res)
	(on_board camera4 rover0)
	(calibration_target camera4 objective4)
	(supports camera4 high_res)
	(supports camera4 low_res)
	(on_board camera5 rover0)
	(calibration_target camera5 objective8)
	(supports camera5 colour)
	(supports camera5 high_res)
	(supports camera5 low_res)
	(on_board camera6 rover0)
	(calibration_target camera6 objective19)
	(supports camera6 colour)
	(visible_from objective0 waypoint0)
	(visible_from objective1 waypoint0)
	(visible_from objective2 waypoint0)
	(visible_from objective3 waypoint0)
	(visible_from objective4 waypoint0)
	(visible_from objective5 waypoint0)
	(visible_from objective5 waypoint1)
	(visible_from objective6 waypoint0)
	(visible_from objective6 waypoint1)
	(visible_from objective7 waypoint0)
	(visible_from objective7 waypoint1)
	(visible_from objective8 waypoint0)
	(visible_from objective9 waypoint0)
	(visible_from objective10 waypoint0)
	(visible_from objective11 waypoint0)
	(visible_from objective11 waypoint1)
	(visible_from objective12 waypoint0)
	(visible_from objective13 waypoint0)
	(visible_from objective13 waypoint1)
	(visible_from objective14 waypoint0)
	(visible_from objective14 waypoint1)
	(visible_from objective15 waypoint0)
	(visible_from objective15 waypoint1)
	(visible_from objective16 waypoint0)
	(visible_from objective16 waypoint1)
	(visible_from objective16 waypoint2)
	(visible_from objective17 waypoint0)
	(visible_from objective17 waypoint1)
	(visible_from objective18 waypoint0)
	(visible_from objective18 waypoint1)
	(visible_from objective18 waypoint2)
	(visible_from objective19 waypoint0)
	(visible_from objective19 waypoint1)
	(visible_from objective19 waypoint2)
	(visible_from objective20 waypoint0)
	(visible_from objective20 waypoint1)
	(visible_from objective20 waypoint2)
	(visible_from objective21 waypoint0)
	(visible_from objective21 waypoint1)
	(visible_from objective21 waypoint2)
	(visible_from objective22 waypoint0)
	(visible_from objective22 waypoint1)
	(visible_from objective22 waypoint2)
	(visible_from objective23 waypoint0)
	(visible_from objective24 waypoint0)
	(visible_from objective24 waypoint1)
	(visible_from objective25 waypoint0)
	(visible_from objective25 waypoint1)
	(visible_from objective25 waypoint2)
	(visible_from objective26 waypoint0)
	(visible_from objective26 waypoint1)
	(visible_from objective26 waypoint2)
	(visible_from objective27 waypoint0)
	(visible_from objective28 waypoint0)
	(visible_from objective28 waypoint1)
)

(:goal (and
(communicated_soil_data waypoint0)
(communicated_soil_data waypoint2)
(communicated_rock_data waypoint2)
(communicated_image_data objective20 high_res)
(communicated_image_data objective18 colour)
(communicated_image_data objective6 high_res)
(communicated_image_data objective24 high_res)
(communicated_image_data objective24 low_res)
(communicated_image_data objective3 high_res)
(communicated_image_data objective14 high_res)
	)
)
)
