(define (problem roverprob200) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 - Rover
	rover0store - Store
	waypoint0 waypoint1 waypoint2 - Waypoint
	camera0 camera1 camera2 camera3 camera4 - Camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 objective8 - Objective
	)
(:init
	(visible waypoint0 waypoint1)
	(visible waypoint1 waypoint0)
	(visible waypoint0 waypoint2)
	(visible waypoint2 waypoint0)
	(visible waypoint2 waypoint1)
	(visible waypoint1 waypoint2)
	(at_rock_sample waypoint0)
	(at_rock_sample waypoint1)
	(at_soil_sample waypoint2)
	(at_lander general waypoint0)
	(channel_free general)
	(at rover0 waypoint2)
	(available rover0)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_soil_analysis rover0)
	(equipped_for_rock_analysis rover0)
	(equipped_for_imaging rover0)
	(can_traverse rover0 waypoint2 waypoint0)
	(can_traverse rover0 waypoint0 waypoint2)
	(on_board camera0 rover0)
	(calibration_target camera0 objective2)
	(supports camera0 colour)
	(supports camera0 low_res)
	(on_board camera1 rover0)
	(calibration_target camera1 objective1)
	(supports camera1 colour)
	(supports camera1 high_res)
	(on_board camera2 rover0)
	(calibration_target camera2 objective8)
	(supports camera2 colour)
	(on_board camera3 rover0)
	(calibration_target camera3 objective6)
	(supports camera3 high_res)
	(on_board camera4 rover0)
	(calibration_target camera4 objective1)
	(supports camera4 high_res)
	(supports camera4 low_res)
	(visible_from objective0 waypoint0)
	(visible_from objective1 waypoint0)
	(visible_from objective2 waypoint0)
	(visible_from objective3 waypoint0)
	(visible_from objective4 waypoint0)
	(visible_from objective5 waypoint0)
	(visible_from objective6 waypoint0)
	(visible_from objective7 waypoint0)
	(visible_from objective8 waypoint0)
	(visible_from objective8 waypoint1)
)

(:goal (and
(communicated_soil_data waypoint2)
(communicated_rock_data waypoint0)
(communicated_image_data objective3 low_res)
(communicated_image_data objective6 low_res)
(communicated_image_data objective6 colour)
(communicated_image_data objective8 colour)
(communicated_image_data objective4 low_res)
(communicated_image_data objective3 colour)
(communicated_image_data objective8 high_res)
	)
)
)
